module Reflex.Resource (
    ResourceContext,
    ResourceT,
    runResourceT,
    runResourceTContext,
    allocate,
    resourceContext,
    -- resourceContextRes,
    -- resourceContextRes',
    -- resourceContextDynRes,
    -- resourceContextDynRes',
    performEventRes,
    performEventRes_,
    -- ** Adjustable-like operations
    ReplaceableResourceContext,
    runWithReplaceContext,
    runWithReplaceRes,
    runWithReplaceRes',
    runWithReplaceDynRes,
    runWithReplaceDynRes',
    traverseIntMapWithKeyWithAdjustContext,
    traverseIntMapWithKeyWithAdjustRes,
    traverseIntMapWithKeyWithAdjustRes',
    traverseIntMapWithKeyWithAdjustDynRes,
    traverseIntMapWithKeyWithAdjustDynRes',
    traverseDMapWithKeyWithAdjustWithMoveContext,
    traverseDMapWithKeyWithAdjustWithMoveRes,
    traverseDMapWithKeyWithAdjustWithMoveRes',
    traverseDMapWithKeyWithAdjustWithMoveDynRes,
    traverseDMapWithKeyWithAdjustWithMoveDynRes',
    dynResReplace,
    dynResIntMap,
    dynResDMap,
    -- ** Temporary context
    TmpResourceContext,
    withTmpContext,
    allocateTmp,

    -- * Res monad
    Res,
    resSampler,
    tmpRes,
    tmpResSampler,
    castRes,
    UnRes,
    toRes,
    fromRes,
    -- ** Adjustable-like operations
    withMaybeRes,
    withMaybeRes',
    withEitherRes,
    withEitherRes',
    whenRes,
    whenRes',
    -- * DynRes monad
    DynRes,
    dynRes,
    dynResDyn,
    dynResSampler,
    castDynRes,
    -- sampling,
    unwrapDynRes,
    toDynRes,
    fromDynRes,
    sampleUnRes,
    -- ** Conditional resources
    withMaybeDynRes,
    withMaybeDynRes',
    withEitherDynRes,
    withEitherDynRes',
    whenDynRes,
    whenDynRes',
    -- ** Adjustable-like operations
    withDynResReplace,
    withDynResReplace',
    -- ** Dynamic-like operations
    module Reflex.Resource.DynRes,
) where

import Reflex.Resource.DynRes
import Reflex.Resource.Internal
